proj4: Intersection.cpp PoliceStation.cpp SafeHouse.cpp WalkEdge.cpp WalkVertex.cpp WalkGraph.cpp proj4.cpp
	g++ Intersection.cpp PoliceStation.cpp SafeHouse.cpp WalkEdge.cpp WalkVertex.cpp WalkGraph.cpp proj4.cpp -o proj4

